{% set name = "echo" %}
{% set version = "0.10.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 97d497a1214dd704d0709dbefd57e48d461ce283f0dca94a9e97b76a2abb3fa7

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy
    - importlib_metadata

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - echo

about:
  home: https://github.com/glue-viz/echo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Callback Properties in Python

extra:
  recipe-maintainers:
    - martinRenou
    - astrofrog
