{% set name = "echo" %}
{% set version = "0.11.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5d5618331b6ac090d097df7aa468f0676cc88fbbbda64a650f42b4a1d80534b9

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy
    - importlib_metadata

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - echo

about:
  home: https://github.com/glue-viz/echo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Callback Properties in Python

extra:
  recipe-maintainers:
    - martinRenou
    - astrofrog
