{% set name = "echo" %}
{% set version = "0.13.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4a4059b38ecbcf67a6a3ffd11c1fa3a71182776d5b9fe15feb91dc928cff13d5

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy
    - importlib_metadata

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - echo

about:
  home: https://github.com/glue-viz/echo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Callback Properties in Python

extra:
  recipe-maintainers:
    - martinRenou
    - astrofrog
