{% set name = "echo" %}
{% set version = "0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 086b523012ea8240ea8a6a061b4934d3a7f2a9fb6d7bef892d3a20d442fce8a2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools_scm
  run:
    - python
    - numpy
    - setuptools
    - qtpy
    - pyqt

test:
  imports:
    - echo
    - echo.qt

about:
  home: https://github.com/glue-viz/echo
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Callback Properties in Python

extra:
  recipe-maintainers:
    - astrofrog-conda-forge
